# Generated by Django 4.2.3 on 2023-08-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Latest', 'Latest'), ('Politics', 'Politics'), ('Crime', 'Crime'), ('Opinion', 'Opinion'), ('Business', 'Business'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Jobs', 'Jobs'), ('Tech', 'Tech')], max_length=50)),
                ('image', models.ImageField(upload_to='photos/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('publishing_time', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='phots/articles')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_article.category')),
            ],
        ),
    ]
