# Generated by Django 4.2.3 on 2023-09-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_article', '0003_alter_rating_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='photos/articles'),
        ),
    ]
