# Generated by Django 4.2.3 on 2023-09-03 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_article', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating_comment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
