# Generated by Django 4.2.3 on 2023-09-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_type',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('editor', 'Editor')], default='Subscriber', max_length=20),
        ),
    ]
